# Generated by Django 4.2 on 2025-12-10 13:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('candidate_name', models.CharField(max_length=200)),
                ('candidate_email', models.EmailField(max_length=254)),
                ('job_position', models.CharField(max_length=200)),
                ('company_name', models.CharField(blank=True, max_length=200)),
                ('company_info', models.TextField(blank=True)),
                ('job_description', models.TextField()),
                ('candidate_resume', models.TextField(help_text='JSON formatted resume or plain text')),
                ('avatar_id', models.CharField(choices=[('female', 'Zeynep'), ('male', 'Mert')], default='female', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Beklemede'), ('active', 'Aktif'), ('completed', 'Tamamlandı'), ('expired', 'Süresi Dolmuş')], default='pending', max_length=20)),
                ('report', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accessed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('external_id', models.CharField(blank=True, help_text='External ATS ID for reference', max_length=200)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='interviewsession',
            index=models.Index(fields=['token'], name='interview_a_token_50de1d_idx'),
        ),
        migrations.AddIndex(
            model_name='interviewsession',
            index=models.Index(fields=['status'], name='interview_a_status_6d1857_idx'),
        ),
        migrations.AddIndex(
            model_name='interviewsession',
            index=models.Index(fields=['created_at'], name='interview_a_created_0104f6_idx'),
        ),
    ]
