# Generated by Django 4.2 on 2025-12-10 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('cv_parser', 'CV Parser'), ('interviewer_system', 'Interview System Prompt'), ('report_generator', 'Report Generator')], help_text='Type of prompt', max_length=50)),
                ('name', models.CharField(help_text='Descriptive name for this prompt', max_length=200)),
                ('system_prompt', models.TextField(help_text='System instructions for the AI')),
                ('user_prompt_template', models.TextField(blank=True, help_text='Template for user prompt (can use {{variables}})')),
                ('is_active', models.BooleanField(default=True, help_text='Only one prompt per type can be active')),
                ('version', models.IntegerField(default=1, help_text='Version number for tracking changes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, help_text='Who created/updated this prompt', max_length=200)),
                ('notes', models.TextField(blank=True, help_text='Notes about this prompt version')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='prompt',
            index=models.Index(fields=['type', 'is_active'], name='interview_a_type_013214_idx'),
        ),
    ]
