# Generated by Django 4.2 on 2025-12-10 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview_api', '0002_prompt_prompt_interview_a_type_013214_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewsession',
            name='ats_api_token',
            field=models.CharField(blank=True, help_text='Encrypted ATS API token', max_length=500),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='ats_data_endpoint',
            field=models.URLField(blank=True, help_text='ATS endpoint to fetch interview data'),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='ats_webhook_url',
            field=models.URLField(blank=True, help_text='ATS webhook URL to send report'),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='last_webhook_attempt',
            field=models.DateTimeField(blank=True, help_text='Last webhook delivery attempt time', null=True),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='temp_report_encrypted',
            field=models.TextField(blank=True, help_text='Temporary encrypted report (only if ATS webhook fails)'),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='temp_report_expires_at',
            field=models.DateTimeField(blank=True, help_text='Auto-delete encrypted report after this time', null=True),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='webhook_last_error',
            field=models.TextField(blank=True, help_text='Last webhook error message'),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='webhook_retry_count',
            field=models.IntegerField(default=0, help_text='Number of webhook delivery attempts'),
        ),
    ]
