# Generated by Django 4.2 on 2025-12-10 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interview_api', '0003_interviewsession_ats_api_token_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('company_name', models.CharField(max_length=200)),
                ('website', models.URLField(blank=True)),
                ('contact_person', models.CharField(blank=True, max_length=200)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('api_key', models.CharField(db_index=True, editable=False, help_text='API key for authentication', max_length=64, unique=True)),
                ('api_key_created_at', models.DateTimeField(auto_now_add=True)),
                ('api_key_last_used', models.DateTimeField(blank=True, null=True)),
                ('plan', models.CharField(choices=[('free', 'Free (10 sessions/month)'), ('pro', 'Pro (100 sessions/month)'), ('enterprise', 'Enterprise (Unlimited)')], default='free', max_length=20)),
                ('quota_monthly', models.IntegerField(default=10, help_text='Monthly session quota')),
                ('quota_used_this_month', models.IntegerField(default=0, help_text='Sessions used this month')),
                ('quota_reset_date', models.DateField(help_text='Date when quota resets')),
                ('is_active', models.BooleanField(default=True)),
                ('is_approved', models.BooleanField(default=True, help_text='Admin approval for new companies')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='duration_seconds',
            field=models.IntegerField(default=0, help_text='Interview duration in seconds'),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Company that owns this session', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='interview_api.company'),
        ),
    ]
