# Generated by Django 4.2 on 2025-12-10 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interview_api', '0010_supportsession'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='supportsession',
            new_name='interview_a_session_183937_idx',
            old_name='interview_a_session_6a8b2c_idx',
        ),
        migrations.RenameIndex(
            model_name='supportsession',
            new_name='interview_a_started_f3550b_idx',
            old_name='interview_a_started_8f3d4e_idx',
        ),
        migrations.RenameIndex(
            model_name='supportsession',
            new_name='interview_a_has_dem_c9607c_idx',
            old_name='interview_a_has_dem_7c9e5f_idx',
        ),
        migrations.RenameIndex(
            model_name='supportsession',
            new_name='interview_a_closure_5bbec8_idx',
            old_name='interview_a_closure_9d2e3a_idx',
        ),
    ]
